apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xy8y0mmlx-go
  janus-idp.io/tekton: xy8y0mmlx-go
  backstage.io/kubernetes-id: xy8y0mmlx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xy8y0mmlx-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
