apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xy8y0mmlx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xy8y0mmlx-go 
  name: xy8y0mmlx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xy8y0mmlx-go 
